# spring:
#   config:
#     activate:
#       on-profile: fifth
# words: Полісся

spring:
  config:
    activate:
      on-profile: fifth
  application:
    name: team-fifth

server:
  port: 8085

words: Ворскла
