# spring:
#   application:
#     name: TEAM

# eureka:
#   client:
#     service-url:
#       defaultZone: http://localhost:8010/eureka

# words: Динамо

spring:
  application:
    name: TEAM

  config:
    import: optional:configserver:http://localhost:8888

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka

words: Динамо

